services:
  - type: web
    name: army-ticket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        generateValue: true